### ISSUE TITLE
Import without a SKY table

### ISSUE THREAD

**Issue by nudomarinero** [revoltek/losoto#10]
In some cases it is not possible to enter an SKY table to create the losoto h5 parmdb file. Although BBS creates the file NDPPP may not create it (see https://github.com/lofar-astron/prefactor/issues/60). In those cases it could be useful to just enter the phase centre of the observation in the "source" table of the solutions. In this case the FIELD table is needed.
If you think that this makes sense I could try to implement it in the importer.

**Comment by AHorneffer** [comment]
The `losotoImporter.py` is actually part of prefactor not losoto. I hope I fixed this in: https://github.com/lofar-astron/prefactor/commit/6327f7f98f437564663e7eb64f654e2d22782e9b

**Comment by nudomarinero** [comment]
Would not https://github.com/revoltek/losoto/blob/master/bin/H5parm_importer.py have the same problem as losotoImporter.py?

**Comment by AHorneffer** [comment]
No, it was already fixed in there.

Btw. if someone approves pull request #11, then we can have both importers running from the same code.

**Comment by nudomarinero** [comment]
OK, thanks. I think it is a good idea to have a common code base.
