### ISSUE TITLE
AttributeError: 'module' object has no attribute 'perf_counter'

### ISSUE THREAD

**Issue by AlexKurek** [revoltek/losoto#103]
Using current master when I try to run Prefactor Im getting at calibrator step:

> 2020-07-27 18:15:48 - DEBUG - [35mAppending to /storage/kurek/native/working_directory/Pre-Facet-Calibrator/instrument.h5imp_cal_PA.[0m
> 2020-07-27 18:15:48 - INFO - [32m--> Starting 'plotP3' step (operation: PLOT).[0m
> Closing remaining open files:
> /storage/kurek/native/working_directory/Pre-Facet-Calibrator/instrument.h5imp_cal_PA...
> 
> 2020-07-27 18:15:48 WARNING node.lof5.executable_args.instrument.h5imp_cal_PA: /opt/LoSoTo//bin/losoto stderr: Traceback (most recent call last):
>   File "/opt/LoSoTo//bin/losoto", line 4, in <module>
>     __import__('pkg_resources').run_script('losoto==2.1', 'losoto')
>   File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 666, in run_script
>     self.require(requires)[0].run_script(script_name, ns)
>   File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1462, in run_script
>     exec(code, namespace, namespace)
>   File "/opt/LoSoTo/lib/python2.7/site-packages/losoto-2.1-py2.7.egg/EGG-INFO/scripts/losoto", line 150, in <module>
>     with operations.Timer(logging, step, op) as t:
>   File "/opt/LoSoTo/lib/python2.7/site-packages/losoto-2.1-py2.7.egg/losoto/operations/__init__.py", line 27, in __enter__
>     self.startcpu = time.perf_counter()
> AttributeError: 'module' object has no attribute 'perf_counter'
> 
> 2020-07-27 18:15:51 ERROR   node.lof5.executable_args: Command '/opt/LoSoTo//bin/losoto' returned non-zero exit status 1

Full log is attached:
[pipeline-Pre-Facet-Calibrator-2020-07-27T15%3A52%3A27.zip](https://github.com/revoltek/losoto/files/4983360/pipeline-Pre-Facet-Calibrator-2020-07-27T15.3A52.3A27.zip)

**Comment by tikk3r** [comment]
It seems `time.perf_counter` was introduced in Python 3.3, so it will not work in genericpipeline pipelines as those only run under Python 2. Perhaps adding a fallback to `time.clock` to maintain compatability is useful.

**Comment by revoltek** [comment]
@AlexKurek what python version do you use?

**Comment by AlexKurek** [comment]
@revoltek For Prefactor I use 2.7.17

**Comment by revoltek** [comment]
The master of losoto is only python 3, I think you need to go back to an older release (1.0)

**Comment by AlexKurek** [comment]
I was able to run entire Prefactor using second to last commit :)

**Comment by tikk3r** [comment]
Fully supporting the move of stuff to Python 3, but I think it is worth noting that this will make losoto unusable in and break prefactor currently, as the genericpipeline does not run under Python 3. This should be fixed once the CWL version is done, but I don't know the status of that.

> I was able to run entire Prefactor using second to last commit :)

Could this commit perhaps be made a 2.1 or some other intermittent release in that case? That would give a nice reference point from where on it no longer works for Python 2 / prefactor.

**Comment by revoltek** [comment]
Hum, there are a large number of python3 specific parts in losoto since release 2.0, I think not all operations work in python2 nor I can be sure of the results. Actually, I really though python2 was not working at all with the latest master. The easiest is to add a 'try' to just account for this

**Comment by tikk3r** [comment]
Ah I didn't realize that. I guess we got extremely lucky the past years then haha.
