### ISSUE TITLE
Colormap not cyclic

### ISSUE THREAD

**Issue by cgroeneveld** [revoltek/losoto#112]
Hi!
https://github.com/revoltek/losoto/blob/9e90647aa6e33ff995b34d606a695debfc767db0/losoto/operations/plot.py#L166

We were wondering why losoto doesn't use a cyclic color map instead of jet (something like twilight or HSV). Maybe it is possible to add a parameter to the parser to select a color map?

Cheers,
Christian

**Comment by revoltek** [comment]
we looked into it some yrs ago but I don't remember what problem with had, maybe there was no cyclic cmap in matplotlib. Anyway @henedler already has this fix done - pushing soon

**Comment by henedler** [comment]
@cgroeneveld I changed the cmap to hsv for cyclic plots now.
