### ISSUE TITLE
pytables 3.3.0 not compatible?

### ISSUE THREAD

**Issue by amisk** [revoltek/losoto#13]
Hello,

While running prefactor it stopped due to errors in losotoimporter.py. I looked deeper into this and the actually error apparently occurs in h5parm.py.

Traceback (most recent call last):
  File "scripts/losotoImporter.py", line 524, in <module>
    solset = parmDBs2h5parm(hdf5File, parmDBnames, antennaFile, fieldFile, skydbFile, compression=compression, solsetName=solsetName)
  File "scripts/losotoImporter.py", line 139, in parmDBs2h5parm
    h5parmDB = h5parm(h5parmName, readonly = False, complevel = compression)
  File "/home/lofar/opt/lofar/lib64/python2.7/site-packages/losoto-0.4-py2.7.egg/losoto/h5parm.py", line 45, in **init**
    self.H = tables.openFile(h5parmFile, filters=f, mode='w', IO_BUFFER_SIZE=1024_1024_10, BUFFER_TIMES=500)
AttributeError: 'module' object has no attribute 'openFile'

We have pytables (python-tables) 3.3.0 installed.

I checked the pytables website and apparently they changed the syntax, so openFile() is now open_file() and createTables() is now create_tables().

I then tried to simply replace them in h5parm.py but this lead to

WARNING:root:Appending to ./h5imp_cal_losoto.h5.
WARNING:root:Solution-set sol000 already present. Switching to default.
ERROR:node.slurm1.python_plugin:group `/sol001` does not have a child named `_f_getChild` 

So, I am not sure if changing is enough.

**Comment by revoltek** [comment]
I upgraded the trunk so this should be fixed (i.e. _f_getChild -> _f_get_child), it should be compatibile with 3.2 and 3.3 now, please let me know if it works like that.

**Comment by tammojan** [comment]
Thanks for fixing it Francesco. Do you know how far backwards compatible it is?

If you add the ticket number #13 in the commit message, it gets linked automatically. For reference, your fix is in fc855fd

**Comment by revoltek** [comment]
It should be compatible with 3.2.2 which is the min required version of pytables for losoto, I did a quick test and it seems fine

**Comment by shulevski** [comment]
I am seeing further issues with the fix it seems. My situation: I have cloned the losoto repo, installed it and got:

> losoto --version
> losoto 0.5

The included losoto tests passed just fine, however prefactor errors out with:

> 2016-11-05 20:50:14 WARNING genericpipeline.executable_args:   from _parmdb import ParmDB
> 2016-11-05 20:50:14 WARNING genericpipeline.executable_args: WARNING:root:No sky table found. (Direction-dependent parameters will not work.)
> 2016-11-05 20:50:14 WARNING genericpipeline.executable_args: WARNING:root:Appending to ./h5imp_gsmsol_losoto.h5.
> 2016-11-05 20:50:14 WARNING genericpipeline.executable_args: WARNING:root:Solution-set sol000 already present. Switching to default.
> 2016-11-05 20:50:19 WARNING genericpipeline.executable_args: ERROR:node.flits-06.python_plugin:group ``/sol002`` does not have a child named ``_f_getChild``
> 2016-11-05 20:50:19 WARNING genericpipeline.executable_args: INFO:node.flits-06.python_plugin:Total time 5.8610s; user time: 3.8677s; system time: 2.6550s
> 2016-11-05 20:50:19 WARNING genericpipeline.executable_args: DEBUG:node.flits-06.python_plugin:Start time was 1478375413.6155s; end time was 1478375419.4766s
> 2016-11-05 20:50:19 ERROR   node.flits-06.python_plugin: group ``/sol002`` does not have a child named ``_f_getChild``
> 2016-11-05 20:50:19 INFO    node.flits-06.python_plugin: Total time 5.8610s; user time: 3.8677s; system time: 2.6550s
> 2016-11-05 20:50:19 WARNING genericpipeline.executable_args: Closing remaining open files:./h5imp_gsmsol_losoto.h5...done

The installed importer.py has the correct changed code:

> c = solset._f_get_child(tab)

**Comment by revoltek** [comment]
ok, this is part of prefactor, not losoto, andreas should be able to fix it quickly

**Comment by tammojan** [comment]
This should be fixed by lofar-astron/prefactor/pull/114
