### ISSUE TITLE
Polalign issues

### ISSUE THREAD

**Issue by jurjen93** [revoltek/losoto#130]
Hi,
I got non-optimal polalign solutions for one of the stations, where I suspect that something goes wrong with the fitting
polalign.png
![image](https://user-images.githubusercontent.com/18346230/176403052-07ed9405-2661-4c8a-a58f-7a29efd935a1.png)

It is a bad station but I think that the fitting could have been done better when looking at the other plots.
You can download the plots, h5, and parset file here:
https://public.spider.surfsara.nl/project/lofarvwf/jdejong/polaligntest.tar.gz

I fixed it by putting the maxResidual on 0.2 (instead of default is 1) but it might be worth to investigate this issue.

**Comment by rvweeren** [comment]
To add a bit more, to me it seems the fitting process is not stable enough for some reason, given how "easy" the input data looks this is worrying.  At least with the default maxResidual and reasonable input the fit should come out fine (for PL612). I wonder if the https://github.com/revoltek/losoto/blob/6082112fd0174444f59cf72b504757ec7c4b12ad/losoto/operations/polalign.py#L125 could cause things to go wrong with a single bad value....

**Comment by rvweeren** [comment]
Another example from Roland, one of the worst I have seen (on 3C196). The input data quality is very high, so the fitting should be very easy.  Despite of that, the residuals after the losoto polalign fit in prefactor look rather bad (everything should be green). 

Input data:
![polalign_ph_poldif](https://user-images.githubusercontent.com/3879473/176726289-3d077af0-1df5-4ca1-91aa-6002a54909dc.png)

The fit:
![polalign](https://user-images.githubusercontent.com/3879473/176726275-a1c0a92b-6089-4565-b054-d69a7759bb18.png)

The residuals:
![polalign_ph-res_poldif](https://user-images.githubusercontent.com/3879473/176725640-655d8002-832f-428a-80bc-3a827d00018a.png)

**Comment by revoltek** [comment]
There's now a more stable algorithm in the master
