### ISSUE TITLE
numpy version dependency

### ISSUE THREAD

**Issue by alxames** [revoltek/losoto#18]
I installed the latest MASTER of losoto on a CentOS 7.2 system which has numpy 1.7.

Before updating to the latest losoto version, one user told me our losoto install doesn't work correctly, because numpy is too old. Your README.md indicates numpy 1.9.0 is needed, but the latest losoto setup does not enforce this and thus my update passes, but I expect the user's problem to persist. (I wasn't told how to reproduce it.)

If there is indeed a numpy version requirement, please enforce it in setup.py.

**Comment by revoltek** [comment]
yes, 1.9 is required for some operations (only a small subset). I will enforce it on the setup.
