### ISSUE TITLE
H5parm_importer.py error for DPPP generated tecandphase solutions gaincal 

### ISSUE THREAD

**Issue by rvweeren** [revoltek/losoto#21]
lofar:/> H5parm_importer.py globaldb_nonDDE allbands.concat.ms
INFO: H5parm filename = globaldb_nonDDE
INFO: globaldb filename = allbands.concat.ms
INFO: Creating a new solution-set: sol000.
INFO: --Creating new antenna table.
INFO: --Creating new source table.
INFO: Found solution types: TEC, CommonScalarPhase
INFO: Reading *ScalarPhase.

Traceback (most recent call last):
  File "/home/rvweeren/.local/bin//H5parm_importer.py", line 103, in <module>
    h5parmFile, complevel, solsetName, globaldbFile=globaldbFile,verbose=options.verbose)
  File "/home/rvweeren/.local/lib/python2.7/site-packages/losoto/importer.py", line 208, in create_h5parm
    data = pdb.getValuesGrid(solType+':*')
  File "/home/rvweeren/software/lofarapr2017/opt/LofIm/lib/python2.7/site-packages/lofar/parmdb/__init__.py", line 201, in getValuesGrid
    stime, etime, asStartEnd)
RuntimeError: Assertion: itsUpper[i-1] <= itsLower[i] || casa::near(itsUpper[i-1],itsLower[i])
Closing remaining open files:globaldb_nonDDE...done

**Comment by nudomarinero** [comment]
How big is allbands.concat.ms? I could have a look into this if I could access a copy of the ms file.

**Comment by rvweeren** [comment]
It's just under 3 GB:

https://www.dropbox.com/s/encwg44lgihzlhw/allbands.concat.ms.tar.gz?dl=0

**Comment by nudomarinero** [comment]
I have downloaded the file and was able to reproduce the problem.

It looks like a problem with the underlying lofar parmdb library and not with losoto. The same error is raised with:
```python
from lofar import parmdb
p = parmdb.parmdb("allbands.concat.ms/instrument/")
p.getValuesGrid("CommonScalarPhase:RS508HBA")
```
Perhaps @tammojan has an idea of why this fails.

**Comment by revoltek** [comment]
Not losoto related
