### ISSUE TITLE
parmdb_collector.py disappeared?

### ISSUE THREAD

**Issue by lmorabit** [revoltek/losoto#23]
Is this script still available somewhere?

**Comment by revoltek** [comment]
you can find it in some old versions of the repository, do you still use it? I can put it back, I thought it was an unused piece of code

**Comment by lmorabit** [comment]
Is there a new method for collecting all the instrument tables into one
global-db that I'm unaware of?

It's also still in the documentation.

**Comment by revoltek** [comment]
No, since that script used the old idea of csv files I removed it, I think so far the best is to implment a small routine that collects parmdbs which is tuned for each case/cluster/pipeline. It is also not far the h5parm implementation in NDPPP, eventually all these issues will be gone!

**Comment by lmorabit** [comment]
Okay, I understand.  I think it's still useful at this point, for people
who aren't running standard pipelines.

**Comment by lmorabit** [comment]
Any chance of getting this script added back in for people who don't have the luxury of an already-built pipeline?

**Comment by revoltek** [comment]
Hi, sorry I forgot about this. I added back the last version we had of it. Try to see if it works ok for what you need. It is in "tools"
