### ISSUE TITLE
statistics wrongly computed for phases/angles

### ISSUE THREAD

**Issue by rvweeren** [revoltek/losoto#24]
Means and median are not correctly computed for phases (leading to serious issues when trying to remove constant phase offsets for example). Maybe rms values for flags/etc are also incorrectly computed.

Code below for circular mean and std.

circular median:

http://www.radiativetransfer.org/misc/atmlabdoc/atmlab/circular/circ_median.html

maybe also : https://raw.githubusercontent.com/circstat/pycircstat/1d034d09d1b64ab23efab36731a808c524b6c67e/pycircstat/descriptive.py

def circ_mean(samples, axis=0):
    '''
    Returns the mean value of a circular array in rad
    in the range [-pi, pi].
    
    Input: List or array of angles in rad
    Output: Scalar of the mean.
    '''
    import numpy as np
    # Normalize angles so that they lie in [0, 2*pi]
    while np.any(samples<0):
        idx = samples<0
        samples[idx] += 2*np.pi
    while np.any(samples>2*np.pi):
        idx = samples>2*np.pi
        samples[idx] -= 2*np.pi
    
    low = 0
    high = 2*np.pi
    
    # calculate mean according to scipy.stats.circmean
    ang = (samples - low)*2*np.pi / (high-low)
    res = np.angle(np.mean(np.exp(1j*ang), axis=axis))
    if np.any(res < 0):
        res = res + 2*np.pi
    return res*(high-low)/2.0/np.pi + low

def circ_std(samples, axis=0):
    import numpy as np
    '''
    Returns the standard deviation value of a circular array in rad
    in the range [-pi, pi].
    
    Input: List or array of angles in rad
    Output: Scalar of the standard deviation.
    '''
    # Normalize angles so that they lie in [0, 2*pi]
    while numpy.any(samples<0):
        idx = samples<0
        samples[idx] += 2*pi
    while numpy.any(samples>2*pi):
        idx = samples>2*pi
        samples[idx] -= 2*pi
    
    low = 0
    high = 2*pi
    
    ang = (samples - low)*2*pi / (high-low)
    res = numpy.mean(numpy.exp(1j*ang), axis=axis)
    V = 1-numpy.abs(res)
    return ((high-low)/2.0/pi) * numpy.sqrt(V)
``

**Comment by revoltek** [comment]
The smooth function now is faster and handle phases correctly
