### ISSUE TITLE
losoto no longer works with prefactor losotoImporter.py

### ISSUE THREAD

**Issue by lmorabit** [revoltek/losoto#35]
The current version of losoto no longer works with the prefactor pipeline, specifically the losotoImporter.py script.  I get the following error:

ImportError: cannot import name solWriter

**Comment by revoltek** [comment]
I guess the problem here is that the losotoimporter.py uses the old API of losoto1.0 instead of the new one. solWriter doesn't exist anymore in 2.0. The solution is to update losotoimporter.py in prefactor to align it with new losoto2.0 API
