### ISSUE TITLE
Too many data points flagged

### ISSUE THREAD

**Issue by mooneyse** [revoltek/losoto#44]
Losoto is crashing on the `CLOCKTEC` operation when I am running it as part of the long-baseline pipeline. The traceback ends with `numpy.linalg.linalg.LinAlgError: Singular matrix`.

I tried running Losoto outside the pipeline on the `.h5` file with verbose mode enabled, and for example it says `DEBUG: Too many data points flagged t=3594 st=18 flags=280[  -1.28172946  467.87407039]`. (It says this ~15,000 times.)

I was wondering is there anything I can do to get the `CLOCKTEC` operation to converge or is there just insufficient data due to flagging?

**Comment by tikk3r** [comment]
I'm seeing this now on a dataset as well. I have already tried different revisions of losoto and NDPPP, but that didn't help.

**Comment by maaijke** [comment]
@mooneyse THanks for the test data. these data have  zeros for all phases so it is no surprise it failed. However, I implemented a sanity check such that losoto will not crash on the particular inverse anymore.

**Comment by tikk3r** [comment]
For the record, https://github.com/revoltek/losoto/commit/df6abf9e4cb3666f363f79e1b840f2e31b886359 fixed the issue for me and the clock/tec separation no longer crashes.
