### ISSUE TITLE
Make a setuptools setup.py

### ISSUE THREAD

**Issue by tammojan** [revoltek/losoto#6]
Would be great to have a setup.py , so that setuptools can install this in the right place. This is also a great way to install dependencies, if they support setuptools.

For example, the selfcal.py script could automatically install losoto like it can install LSMTool, see https://github.com/nicolasvilchez/pyselfcal/blob/master/setup.py

**Comment by nudomarinero** [comment]
There is a branch where I packaged losoto as a module with the setup.py script https://github.com/revoltek/losoto/tree/tests_jsm
It is obsolete now, but I could try to recreate the functionality if needed.

**Comment by tammojan** [comment]
> It is obsolete now, but I could try to recreate the functionality if needed.

That would be great.

**Comment by nudomarinero** [comment]
Hello again, 
You can try the new setup.py in the branch "module" as indicated in #7
