### ISSUE TITLE
Treat rotation as phase-like solutions

### ISSUE THREAD

**Issue by tikk3r** [revoltek/losoto#63]
The values in rotation should be handled like phases in e.g. reweight.py.

@rvweeren

**Comment by rvweeren** [comment]
This refers to 

https://github.com/revoltek/losoto/blob/436cb32af09fd542d999ae888bfa7dc9886da8b1/losoto/operations/reweight.py#L93

**Comment by rvweeren** [comment]
suggestion:
<code>
if type == 'phase' or type == 'rotation':
