### ISSUE TITLE
plotting phases with reference antenna that is entirely flagged

### ISSUE THREAD

**Issue by rvweeren** [revoltek/losoto#64]
A feature request for losoto. For the plotting operation regarding phases/rotations: it would be useful if the code automatically switches to another reference station if the provided reference station is fully flagged. If we run the prefactor pipeline automatically for many observations we do not want to be caught by our choice for reference station in the plotting.

Would this be useful?

(otherwise we would need to make a separate python script for prefactor to automatically select a good reference station for plotting, but I think it is better if we avoid separate python scripts here)

**Comment by revoltek** [comment]
it would be useful. Many operations have a refant, best thing would be to code a utility function (in lib_operations.py) that check if the user provided refant is OK, otherwise return the "best" one (instead of the first, which is the current behavior). The problem is to make the check quick if the dataset is large.

**Comment by rvweeren** [comment]
Just to note that this again caused everything to get flagged in a recent prefactor run because CS001HBA0/1 was not working. Maybe it needs fixing in prefactor but it needs fixing somewhere.

**Comment by revoltek** [comment]
I added a "reference" operation where if no antenna is specified it references the table to the most unflagged antenna. Note that this is a separate operation that needs to be run before any operation that requires referencing and refAnt needs to be removed from these other operations. I would avoid adding such a check each time a referencing is required as it is done often and it would take quite some time to fetch all weights to check the flags
