### ISSUE TITLE
H5parm2parmdb.py gives error

### ISSUE THREAD

**Issue by lmorabit** [revoltek/losoto#65]
I have a parmdb that I convert to an h5parm and now I need to convert it back to a parmdb so I can run a script on it.  I am trying to use H5parm2parmdb.py but I haven't had any luck.  On CEP3, I am using the /home/fdg/losoto distribution, which gives the following error:

[lmorabit@lof012 test_h5parm_to_parmdb]$ H5parm2parmdb.py -V -c test.h5 ILTJ134934.6+534117.9_L401323_SB244_uv.dppp_12723A7FEt_122MHz.msdpppconcat
INFO: Input H5parm filename = test.h5
DEBUG: Reading from test.h5.
INFO: Input globaldb/SB filename = ILTJ134934.6+534117.9_L401323_SB244_uv.dppp_12723A7FEt_122MHz.msdpppconcat
INFO: Solution set name = sol000
INFO: Output globaldb/SB filename = ILTJ134934.6+534117.9_L401323_SB244_uv.dppp_12723A7FEt_122MHz.msdpppconcat
Traceback (most recent call last):
  File "/home/fdg/losoto/bin/H5parm2parmdb.py", line 420, in <module>
    solTabList = getSoltabFromSolType(solType, solTabs, 'ampl')
  File "/home/fdg/losoto/bin/H5parm2parmdb.py", line 140, in getSoltabFromSolType
    if hasattr(st._v_attrs, 'parmdb_type'):
  File "/home/fdg/losoto/losoto/h5parm.py", line 1058, in __getattr__
    return object.__getattribute__(self, axis)
AttributeError: 'Soltab' object has no attribute '_v_attrs'
Closing remaining open files:test.h5...done

Any help you could provide would be appreciated.

**Comment by revoltek** [comment]
Hum, no idea... I think I've to look at the parmdb and the h5parm, the but might be in anyone of the two

**Comment by lmorabit** [comment]
It's on CEP3 at /data012/scratch/LB_BW_Aug2018/test_h5parm_to_parmdb if you would like to have a look, although I don't know if you can reproduce the error elsewhere.

**Comment by lmorabit** [comment]
was this issue resolved?  could you reproduce the error?

**Comment by revoltek** [comment]
yes, I think it's fixed now
