### ISSUE TITLE
flag replace option fails

### ISSUE THREAD

**Issue by rvweeren** [revoltek/losoto#68]
vals_detrended never gets assigned/made anywhere in flag.py.....

(so it gives this error:   File "/home/rvweeren/.local/lib/python2.7/site-packages/losoto/operations/flag.py", line 206, in outlier_rej
    vals[orig_weights != weights] = vals_detrended
NameError: global name 'vals_detrended' is not defined
)

https://github.com/revoltek/losoto/blob/eef245104d4fafdb27ef356c9747fd7e5b3e9e3b/losoto/operations/flag.py#L206

**Comment by rvweeren** [comment]
I tried fixing it with by changing 

`vals_detrended` to `vals_detrend`.

However, then I get a other errors....did "replace" work in the past or is this completely untested?


 self.run()
  File "/home/rvweeren/.local/lib/python2.7/site-packages/losoto/lib_operations.py", line 35, in run
    self.funct(*parms, outQueue=self.outQueue)
  File "/home/rvweeren/.local/lib/python2.7/site-packages/losoto/operations/flag.py", line 255, in _flag
    weights, vals, rms = outlier_rej(np.log10(vals), weights, flagCoord, order, mode, maxCycles, maxRms, maxRmsNoise, windowNoise, fixRmsNoise, replace)
  File "/home/rvweeren/.local/lib/python2.7/site-packages/losoto/operations/flag.py", line 206, in outlier_rej
    vals[orig_weights != weights] = vals_detrend
ValueError: NumPy boolean array indexing assignment cannot assign 24 input values to the 0 output values where the mask is true

**Comment by revoltek** [comment]
the first was most likely a typo, I fixed it. For the second, it is a bug. The replace has been used very rarely. I will tr to fix it now.
