### ISSUE TITLE
example soltabToAdd wrong

### ISSUE THREAD

**Issue by rvweeren** [revoltek/losoto#71]
For some reason losoto does not accept "sol000/tec000" but only "tec000" for soltabToAdd (so the sol000 cannot be specified)

https://github.com/revoltek/losoto/blob/3f3bc28960a09c8ab10817614eaf351ab957bee0/parsets/losoto2.parset#L102

**Comment by revoltek** [comment]
That all thing "soltabToAdd" needs to be re-implemented. I was working on it in the last days, but it's totally non trivial, now if you use it it return a warning says that that functionality is not implemented.

**Comment by rvweeren** [comment]
Oh, so I should not update my losoto installation :-)
 soltabToAdd = tec000 is working for my specific case. (but not  soltabToAdd = sol000/tec000)

**Comment by revoltek** [comment]
Yes, to works only in certain cases, if you have the axes in the right order etc, but not generally, that's why I had to comment it out
