### ISSUE TITLE
operation smooth phases not robust with flagged reference antenna 0

### ISSUE THREAD

**Issue by rvweeren** [revoltek/losoto#72]
A proper reference antenna needs to be set to smooth phases, in particular when reference antenna 0 is flagged and has no data. In my case I had CS001HBA0 flagged so effectively there does not seem to be any reference antenna (and that seems to negatively affect the phase smoothing)

**Comment by revoltek** [comment]
What mode did you use? I see that by default we don't reference in any mode, which is indeed a problem for the median/mean, while the runningmedian is currently done in real/image space for phases, that should be ok.

**Comment by revoltek** [comment]
I fixed a bug in the smooth on phases, now one can reference to an arbitrary antenna (before it was not possible). It seems to work (I tested with median).
