### ISSUE TITLE
Parallelization of clock/TEC separation

### ISSUE THREAD

**Issue by tikk3r** [revoltek/losoto#76]
More a feature request. Clock/TEC separation only uses 1 core at the moment, which in e.g. the long baseline pipeline takes quite a while. A parallel implementation will save a lot of time, if possible.

**Comment by revoltek** [comment]
@maaijke :)

**Comment by maaijke** [comment]
I added a field nproc that sets the number of processes used, default =10, maximum should be the number of antennas.  Since memory usage per process can be large (at least for the huge datafile I got from fdg)  this should be tested

**Comment by tikk3r** [comment]
I played around with it a bit this morning  and it works as expected for me. Thanks and sorry it took me a while to get back to this!
