### ISSUE TITLE
TypeError: can't multiply sequence by non-int of type 'float'

### ISSUE THREAD

**Issue by HannoSpreeuw** [revoltek/losoto#78]
Running prefactor on this calibrator (3C295) dataset (LC0_043, SASid 151876, L151880*.MS, 244 subbands) gives 

> 2018-12-21 11:04:12 INFO    genericpipeline.executable_args: Waiting for compute threads...
2018-12-21 11:04:45 WARNING node.fs5.executable_args.instrument.h5imp_cal: /opt/losoto/bin/losoto stderr: INFO: --> Starting 'clocktec' step (operation: CLOCKTEC).
INFO: Clock/TEC separation on soltab: phase000
INFO: Creating a new solution-table: tec000.
INFO: Creating a new solution-table: clock000.
INFO: Creating a new solution-table: phase_offset000.
INFO: Step 'clocktec' completed successfully.
INFO: Time for this step: 25 s (cpu: 76 s).
INFO: --> Starting 'clock_smooth' step (operation: SMOOTH).
INFO: Smoothing soltab: clock000
INFO: Writing results...
INFO: Step 'clock_smooth' completed successfully.
INFO: Time for this step: 0 s (cpu: 0 s).
INFO: --> Starting 'bandpass' step (operation: PREFACTOR_BANDPASS).
INFO: Running prefactor_bandpass on: amplitude000
INFO: Have 307.0 subbands.
INFO: Creating a new solution-table: bandpass.
INFO: Step 'bandpass' completed successfully.
INFO: Time for this step: 6 s (cpu: 6 s).
INFO: --> Starting 'xyoffset' step (operation: PREFACTOR_XYOFFSET).
INFO: Running XYoffset on: phase000
Traceback (most recent call last):
  File "/opt/losoto/bin/losoto", line 4, in <module>
    __import__('pkg_resources').run_script('losoto==2.0', 'losoto')
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 664, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1444, in run_script
    exec(code, namespace, namespace)
  File "/opt/losoto/lib/python2.7/site-packages/losoto-2.0-py2.7.egg/EGG-INFO/scripts/losoto", line 145, in <module>
    returncode += ops[ op ]._run_parser( soltab, parser, step )
  File "/opt/losoto/lib/python2.7/site-packages/losoto-2.0-py2.7.egg/losoto/operations/prefactor_XYoffset.py", line 14, in _run_parser
    return run(soltab, chanWidth)
  File "/opt/losoto/lib/python2.7/site-packages/losoto-2.0-py2.7.egg/losoto/operations/prefactor_XYoffset.py", line 73, in run
    offsetHz = subbandHz / 2.0 - 0.5 * chanWidthHz
TypeError: can't multiply sequence by non-int of type 'float'

**Comment by HannoSpreeuw** [comment]
I can supply the pipeline.cfg and Pre-Facet-Calibrator.parset.
I am running this from [a Singularity container](https://github.com/tikk3r/lofar-grid-hpccloud/issues/7#issuecomment-449460827).

**Comment by revoltek** [comment]
This is a prefactor-specific operation (that will also be removed in new prefactor3). @darafferty @adrabent what do you think?

**Comment by adrabent** [comment]
@revoltek Indeed.. the master branch of prefactor is not updated anymore.
You are free to test the branch `version3.0`.

But nevertheless.. what is your variable: `chanWidthHz`?

**Comment by HannoSpreeuw** [comment]
I guess the value of chanWidthHz follows from this setting in Pre-Facet-Calibrator.parset:
`! avg_freqresolution       =  48.82kHz  ## average to 48.82 kHz/ch (= 4 ch/SB)`

**Comment by tikk3r** [comment]
It comes from here (lines 37 and 223-229 from Pre-Facet-Calibrator):
```
! avg_freqresolution = 48.82kHz ## average to 48.82 kHz/ch (= 4 ch/SB)
```
```
prepare_losoto.control.bandpass.soltab               =   [sol000/amplitude000]
prepare_losoto.control.bandpass.operation            =   PREFACTOR_BANDPASS
prepare_losoto.control.bandpass.chanWidth            =   {{ avg_freqresolution }}
prepare_losoto.control.bandpass.BadSBList            =   {{ bad_SB_list }}
prepare_losoto.control.xyoffset.soltab               =   [sol000/phase000]
prepare_losoto.control.xyoffset.chanWidth            =   {{ avg_freqresolution }}
prepare_losoto.control.xyoffset.operation            =   PREFACTOR_XYOFFSET
```

Everything except `chanWidthHz` on that line is a number. Leaving it as a string results in the same error, however:
```python
In [3]: 195.3125e3 / 2.0 - 0.5 * '48.82kHz'
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-3-df6422ce7884> in <module>()
----> 1 195.3125e3 / 2.0 - 0.5 * '48.82kHz'

TypeError: can't multiply sequence by non-int of type 'float'
```
Is it possible `chanWidthHz` somehow slips through as a string?

**Comment by HannoSpreeuw** [comment]
That is certainly possible.
Not sure how to fix it. Perhaps remove the "kHz":
`! avg_freqresolution = 48.82 ## average to 48.82 kHz/ch (= 4 ch/SB)`
?

**Comment by HannoSpreeuw** [comment]
This is the relevant snippet of code from prefactor_XYoffset.py:
`   subbandHz = 195.3125e3
    if type(chanWidth) is str:
        letters = [1 for s in chanWidth[::-1] if s.isalpha()]
        indx = len(chanWidth) - sum(letters)
        unit = chanWidth[indx:]
        if unit.strip().lower() == 'hz':
            conversion = 1.0
        elif unit.strip().lower() == 'khz':
            conversion = 1e3
        elif unit.strip().lower() == 'mhz':
            conversion = 1e6
        else:
            logging.error("The unit on chanWidth was not understood.")
            raise ValueError("The unit on chanWidth was not understood.")
        chanWidthHz = float(chanWidth[:indx]) * conversion
    else:
        chanWidthHz = chanWidth
    offsetHz = subbandHz / 2.0 - 0.5 * chanWidthHz
`

**Comment by adrabent** [comment]
@HannoSpreeuw
Unfortunately I can not reproduce the error if I use `chanWidth = 48.82 kHz`. My script runs through smoothly. `chanWidthHz` is a float by definition (see line 70) as well as `subbandHz` (see line 56).
Could you dig into your losoto directory and try to do some print debugging. What is the value of both variables right before line 73?

**Comment by darafferty** [comment]
@adrabent: It looks like you might have fixed this issue with commit 170902fba93293258e67596c9ee204c21947bc3a

**Comment by adrabent** [comment]
True, but this line disapperead again in the most recent version:
https://github.com/revoltek/losoto/blob/master/losoto/operations/prefactor_XYoffset.py

**Comment by darafferty** [comment]
Sorry, I initially confused prefactor_bandpass.py with prefactor_XYoffset.py -- it seems to be fixed in the former but not the latter.

**Comment by adrabent** [comment]
@darafferty ...okay.. thanks for the hint!
@HannoSpreeuw .. please report if the newest commit fixes your issue

**Comment by HannoSpreeuw** [comment]
That fixed it! Thanks.
