### ISSUE TITLE
flagstation residual phases

### ISSUE THREAD

**Issue by wllwen007** [revoltek/losoto#81]
Shouldn't flagging stations based the phase residuals (flagstation mode='resid') be using (or be able to use) a reference station? It seems to have the option to set a refAnt, but it doesn't seem to use it anywhere?

See also https://github.com/lofar-astron/prefactor/issues/209

**Comment by darafferty** [comment]
Yes, well spotted -- I intended to implement that option but somehow forgot. I've pushed a fix for it -- please update and let me know if it works now.

**Comment by wllwen007** [comment]
Thanks! I had to add a fix to the fix , but it seems to work now.

Possibly the maxStddev (hardcoded to 0.1 rad) is a bit high, at least for LBA data...

**Comment by darafferty** [comment]
OK, thanks. Probably the user should be able to set maxStddev. I'll add an option for that.
