### ISSUE TITLE
makeSoltab error

### ISSUE THREAD

**Issue by Joshuaalbert** [revoltek/losoto#82]
Hi Fra, the following 
``` python
H = h5parm(filename, readonly=False)
H.makeSolset(solsetName=solset, addTables=True)
solset = H.getSolset(solset)
solset.makeSoltab(name, axesNames=['pol', 'dir', 'ant', 'time'],
                                        axesVals=[pols, dirs, ants, times], 
                                        vals=vals, weights=np.ones_like(vals),
                                        weightDtype='f64')
```
Gives the following traceback,
``` bash
  File "/home/albert/miniconda3/envs/bayes_filter/lib/python3.7/site-packages/losoto-2.0-py3.7.egg/losoto/h5parm.py", line 487, in makeSoltab
    soltabName = self._fisrtAvailSoltabName(soltype)
  File "/home/albert/miniconda3/envs/bayes_filter/lib/python3.7/site-packages/losoto-2.0-py3.7.egg/losoto/h5parm.py", line 545, in _fisrtAvailSoltabName
    for soltab in self.getSoltabs():
  File "/home/albert/miniconda3/envs/bayes_filter/lib/python3.7/site-packages/losoto-2.0-py3.7.egg/losoto/h5parm.py", line 569, in getSoltabs
    for soltab in self.obj._v_groups.itervalues():
RuntimeError: generator raised StopIteration
```

## Settings
python 3.X
```python
import tables
tables.__version__
Out[14]: '3.4.5.dev0'
```

**Comment by revoltek** [comment]
It works on python 2.7, not sure for python 3. I still have to fully port losoto to python 3

**Comment by revoltek** [comment]
#29

**Comment by Joshuaalbert** [comment]
Okay, weird,  it used to work. I've been using this same code for 6 months or so. Was there an alteration to losoto.h5parm recently? Alternatively, have you tested with pytables 3.4.X? I recently compiled hdf5 and  tables.

**Comment by tikk3r** [comment]
Did you recently update to 3.7? There's this:

>PEP 479 is enabled for all code in Python 3.7, meaning that StopIteration exceptions raised directly or indirectly in coroutines and generators are transformed into RuntimeError exceptions. (Contributed by Yury Selivanov in bpo-32670.)

so it might even be one of the dependencies.

**Comment by Joshuaalbert** [comment]
@tikk3r , that could be the case. I am using 3.7 recently. Then I'm wondering if I can simply hack a fix for this... I guess pytables is using StopIteration wrongly at the moment?

**Comment by tikk3r** [comment]
Not sure, I haven't made the switch to 3 fully myself yet either. It could be some code somewhere that used to work that now needs a bit of tweaking somewhere.

**Comment by revoltek** [comment]
I tested some basic thing with 3.7 now and it seems to work

**Comment by Joshuaalbert** [comment]
Ah wow, this is great! Will verify soonOn 18 Feb 2019 7:37 p.m., Francesco de Gasperin <notifications@github.com> wrote:I tested some basic thing with 3.7 now and it seems to work
