### ISSUE TITLE
losoto flags all good solutions

### ISSUE THREAD

**Issue by rvweeren** [revoltek/losoto#85]
I have been debugging an issue in my pipeline where sometimes all solutions gets flagged. It turns out this is happens at a losoto phase flagging step. Just:

```
[flagphase]
soltab = [sol000/phase000]
operation = FLAG
axesToFlag = [time,freq]
mode = smooth
maxCycles = 1
windowNoise = 7
maxRms = 7.
order  = [5,5]

```
and all my output phase solutions are flagged (it is not a reference stations issue). I have attached a h5 file and parset that reproduces the bug.
[losotoissue.tar.gz](https://github.com/revoltek/losoto/files/2895998/losotoissue.tar.gz)

Below the before and after phase matrix plots (my suspicion it that the bug is NaN related).

![slowphasedirpointing_polyy](https://user-images.githubusercontent.com/3879473/53273890-9e2ac000-36f5-11e9-8ba8-980d809bfab4.png)
![phaseflaggeddirpointing_polyy](https://user-images.githubusercontent.com/3879473/53273901-a8e55500-36f5-11e9-95a6-26fc347c23af.png)

**Comment by rvweeren** [comment]
Confirmed the problem is related to some NaN solution values in the H5.

**Comment by revoltek** [comment]
Most likely are nans that are not flagged (weights != 0) this is a problem with recent DP3. A workaround is to use H5parm_collector that flags all nans
