### ISSUE TITLE
progressbar import fails

### ISSUE THREAD

**Issue by alxames** [revoltek/losoto#9]
I've installed losoto and set my PYTHONPATH correctly. I think the install is mostly correct since importing losoto or its parts (e.g. losoto.h5parm, losoto.operations, ...) appear to work. The following fails however:
```
In [3]: import losoto.progressbar
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-3-2ccd98a29ddd> in <module>()
----> 1 import losoto.progressbar

/home/USERNAME/pkg/losoto-tmpinst/lib/python2.7/site-packages/losoto-1.0.0-py2.7.egg/losoto/progressbar/__init__.py in <module>()
     56     pass
     57 
---> 58 from progressbar.compat import *
     59 from progressbar.widgets import *
     60 

ImportError: No module named progressbar.compat
```

While I don't need to do that import, I install losoto for others and then do some basic checks to see if installation or upgrade worked correctly. Losoto may do a similar import itself.

Could it be that you took progressbar from some other pkg in a way that is not entirely error free. (?)

**Comment by mhardcastle** [comment]
Have you tried 'pip install progressbar'?

**Comment by alxames** [comment]
Thanks. I see what's up: losoto always does this:
```
    try:
        import progressbar
    except ImportError:
        import losoto.progressbar as progressbar
```

So 'pip install progressbar' (or in my case preferably 'yum install python-progressbar') may solve any errors we may get using losoto.

But why ship progressbar along?
Better add progressbar to the setup.py install_requires (or so) and remove the shipped copy as a sub-pkg and the try/except construct above. Now, a successful install may not work due to a missing dependency.

**Comment by nudomarinero** [comment]
Yes, I think progressbar is better added to the requirements. I can do that if Francesco agrees.

**Comment by revoltek** [comment]
Hi, the idea was to add that package as part of the code so to reduce the problems for other people to look for and install it. I have probably done it in the wrong way. Pepe do you have a clean way to handle this?

**Comment by nudomarinero** [comment]
OK. I think it is easy to fix the problem with the bundled progressbar version.
I added the try...except blocks to use the system progressbar and only fall back to the bundled version when it was not found. 
I think that, in any case, we should add progressbar as a dependence.

**Comment by nudomarinero** [comment]
The last two commits should fix the problem. Now progressbar is a dependence and, in the unlikely case that it is not installed, losoto should correctly fall back to the bundled version that should be fixed.
