### ISSUE TITLE
MemoryError with H5parm_collector

### ISSUE THREAD

**Issue by mknapp55** [revoltek/losoto#94]
I'm trying to run H5parm_collector on a LOFAR calibrator observation (243 SB) to make one consolidated h5 file.  Towards the end of the script execution, I get python's MemoryError.  I have 64 GB of RAM and 12 cores on the machine I'm using.  In your experience, do I need even more memory to run H5parm_collector on a typical LOFAR LBA calibrator observation?  I'm using losoto installed from the master branch.

For reference, here's the traceback:
```
2019-08-06 19:08:02 - DEBUG: Fetching info for amplitude000.
Traceback (most recent call last):
  File "/usr/local/bin/H5parm_collector.py", line 4, in <module>
    __import__('pkg_resources').run_script('losoto==2.0', 'H5parm_collector.py')
  File "/home/mknapp/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 664, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/mknapp/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1444, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/losoto-2.0-py2.7.egg/EGG-INFO/scripts/H5parm_collector.py", line 165, in <module>
    logging.info(str(h5Out))
  File "/usr/local/lib/python2.7/dist-packages/losoto-2.0-py2.7.egg/losoto/h5parm.py", line 116, in __str__
    return self.printInfo()
  File "/usr/local/lib/python2.7/dist-packages/losoto-2.0-py2.7.egg/losoto/h5parm.py", line 365, in printInfo
    info += '    Flagged data: %.3f%%\n' % (100.*np.sum(weights==0 | np.isnan(vals))/len(weights.flat))
MemoryError
Closing remaining open files:/mnt/d/lofar/V830Tau/workdir_L693116/cal-pa.h5...done
```

**Comment by revoltek** [comment]
Hum, it crashes when it loads the flag info into memory. This is strange, it shouldn't be so much data, however I have never tried to run the pipeline in a machine with only 64 GB memory. Can you try the master branch? I am a bit worried that if this step is memory critical, then you might encounter similar problems in other steps as well...

**Comment by mknapp55** [comment]
I'm using the master branch - I updated and reran setup before trying this again today.  Same result.  

This was the command:
```
H5parm_collector.py -V -s sol000 -o /mnt/d/lofar/V830Tau/workdir_L693116/cal-pa.h5 /mnt/d/lofar/V830Tau/workdir_L693116/L693116_SB???_uv.MS/pa.h5 --clobber
```

When the console showed this debug statement:
`2019-08-08 14:30:20 - DEBUG: Fetching info for amplitude000.`

Htop showed this:
![IMG_3572](https://user-images.githubusercontent.com/4721894/62728771-98e2d880-b9ea-11e9-9742-71fed2dfb265.JPG)

May I ask how much RAM the machine/cluster you typically use has?  If 64 GB isn't enough, I'd like to get an idea of how much would be enough so I can find the appropriate resource.

**Comment by revoltek** [comment]
I've 128->512, no problem noticed in machine with that range of memory. I admit probably this can be fixed, but I currently have very little time to work on losoto...
